### ISSUE TITLE
How to handle events and get the user's rate ?

### ISSUE THREAD

**Issue by teruun** [dreyescat/react-rating#10]
I added code below in my jsx
`<Rating onClick={rating => this.handleRate(rate)} />`
and browser console says the rate is not defined. How should I define this rate variable? Or how can I interact with this component to get user's rate value?
Sorry for such a dumb question and it will be nice to help me with this problem. Thanks in advance.

**Comment by dreyescat** [comment]
Hi @teruun.

The function you pass to the `onClick` property is not using the `rating` parameter but an `undefined` one (`rate`). Try this:

```javascript
<Rating onClick={rate => this.handleRate(rate)} />
```

Hope it helps.

**Comment by teruun** [comment]
wow @dreyescat   
It helps.  Thank you very much!
