### ISSUE TITLE
Click event swallowed even when readony / noop onClick

### ISSUE THREAD

**Issue by exogen** [dreyescat/react-rating#100]
As mentioned in #98, we're rendering `readonly` ratings inside of links, which take you to the product's reviews page.

We found that if you click directly on one of the stars, the click event gets swallowed, so it doesn't bubble up to the link element. (For some reason, this only seems to happen for `touch` events and not `click` events, which is very mysterious to me since the same react-rating code runs for both. So only mobile clicks are swallowed.)

I believe this is due to this block here: https://github.com/dreyescat/react-rating/blob/master/src/RatingSymbol.jsx#L55-L60

My guess is the original intention was that for `readonly` ratings, no `onClick` would be passed at all and thus the event would never be swallowed. But instead of passing nothing, react-rating passes a `noop` onClick function, thus the event is always swallowed whether or not react-rating is actually going to do anything with the click.

One fix would be to stop using the `noop` function here, or check for it explicitly in addition to `if (onClick)`.

For anyone looking for a workaround: we currently wrap `react-rating` with another component that sets `pointer-events: none` if `readonly` is passed, so `RatingSymbol` never gets the event to call `preventDefault` on it in the first place.

**Comment by dreyescat** [comment]
> My guess is the original intention was that for readonly ratings, no onClick would be passed at all and thus the event would never be swallowed. But instead of passing nothing, react-rating passes a noop onClick function, thus the event is always swallowed whether or not react-rating is actually going to do anything with the click.

You are completely right. That was the idea. We shouldn't pass a handler for readonly ratings.

**Comment by dreyescat** [comment]
Released in version [1.2.1](https://github.com/dreyescat/react-rating/releases/tag/v1.2.1).
