### ISSUE TITLE
Need set spacing between stars via prop. 

### ISSUE THREAD

**Issue by zhrvdns** [dreyescat/react-rating#103]
Need set spacing between stars via prop.

**Comment by dreyescat** [comment]
Do you mean having a margin between stars? A sort of *no man's land* area between symbols? What should be the behavior when clicking/hovering over this area? I think that symbols must cover the whole component area.

The rating component allows you complete customization of your symbols. Just add some padding in your symbols via css attributes or via react properties.

Here you have a contrived example:

```javascript
const style = {
  width: '32px',
  fontSize: '2em',
  padding: '0 5px'
};
const EmptySymbol = () => <div style={style}>+</div>;
const FullSymbol = () => <div style={{...style, color: 'red'}}>+</div>;

<Rating
    emptySymbol={<EmptySymbol />}
    fullSymbol={<FullSymbol />}
/>
```

Check the [codepen](https://codepen.io/dreyescat/pen/ajBodw).

**Comment by zhrvdns** [comment]
Thanks!

**Comment by spacecat** [comment]
Tried the code pen and it does not work with fractions. For example:

```
<Rating
    emptySymbol={<EmptySymbol />}
    fullSymbol={<FullSymbol />}
    initialRating={3.7}
    readonly
  />
```
Notice that the full symbol area is off. For example; if you set the rating to 3.5 then half the plus sign should be filled but it isn't.

Are there any other ways to do this?
