### ISSUE TITLE
Module broken on server-side since 1.3.1

### ISSUE THREAD

**Issue by PepijnSenders** [dreyescat/react-rating#105]
I just upgraded to `1.3.1` and noticed that my app broke on the server. I have an import on a component that is rendered both on server as client-side and now it breaks with `ReferenceError: window is not defined`.

I checked out the changes and it seems like that it broke on [this line](https://github.com/dreyescat/react-rating/commit/010a29cc8c131750f3c1dafd7c9d23e3f752fe4c#diff-0774e101382e9f112bd212d69853021bR11), probably @dreyescat is using a different kind of compiling suddenly.

**Comment by dreyescat** [comment]
The `umd` target generates invalid code for running inside a Node.js context. The global object is set to `window`. As a workaround, we force it to be as the documentation about [Module Definition Systems](https://webpack.js.org/configuration/output/#output-librarytarget) states:

```javascript
typeof self !== 'undefined' ? self
```

This is the expected output for `umd` modules:

```javascript
(function webpackUniversalModuleDefinition(root, factory) {
  if(typeof exports === 'object' && typeof module === 'object')
    module.exports = factory();
  else if(typeof define === 'function' && define.amd)
    define([], factory);
  else if(typeof exports === 'object')
    exports['MyLibrary'] = factory();
  else
    root['MyLibrary'] = factory();
})(typeof self !== 'undefined' ? self : this, function() {
  return _entry_return_;
});
```

Released in [1.3.2](https://github.com/dreyescat/react-rating/releases/tag/v1.3.2)

**Comment by dreyescat** [comment]
@PepijnSenders This workaround should fix your issue. Let me know otherwise.

**Comment by PepijnSenders** [comment]
Okay, I compile it with `target: "node"` though, shouldn't it then also compile the code without the `window` variable?

**Comment by PepijnSenders** [comment]
(I have two bundles, one for the server and one for the client)

**Comment by dreyescat** [comment]
I am not sure I understand what you mean... Let me know if I have missed the point 😅.

> Okay, I compile it with target: "node" though, shouldn't it then also compile the code without the window variable?

Yes. I think the difference between `target: "node"` and no target specified (defaults to `target: "web"`) is what globalObject is used. That is, `global` for node and `window` for web.

But... What are you *compiling*? The `react-rating` lib is already *compiled*. I assume you are only compiling your application code, right? So, you are not compiling the `react-rating` lib again. Only your code is being compiled while the `react-rating` lib code is inserted as is. No target affects the lib code.

If you want to compile the library again using your own configuration file then you should use the `src`. I am not sure how is it done but I remember a pull request #40 requesting to include source in `package.json` to *allow other to rebuild / webpack when needed*.

**Comment by dreyescat** [comment]
By the way... Is this workaround not working for you? Would it work if the globalObject was `this`:

```javascript
})(this, function() {
  return _entry_return_;
});
```

instead of the `typeof self !== 'undefined' ? self : this` expression:

```javascript
})(typeof self !== 'undefined' ? self : this, function() {
  return _entry_return_;
});
```

**Comment by msreekm** [comment]
trying to use this library in my next.js project - (SSR)

{ ReferenceError: window is not defined}

**Comment by dreyescat** [comment]
@msreekm Sorry. I forgot to publish the new version 1.3.2 that is supposed to solve this issue. Would you mind to try again with the new version?
