### ISSUE TITLE
Custom icons not working properly (spacing issue)

### ISSUE THREAD

**Issue by ScottAgirs** [dreyescat/react-rating#107]
Awesome job on the package!

Hopefully it's just something that I'm missing ..

I tried FontAwesome (with CDN import) and with installing the react package with npm i.
I use React Semantics for my project, and example provided are that too.

**This works:** ( .. name="star" ..)

```
import Rating from "react-rating";
import { .. Icon } from "semantic-ui-react";
..
<Rating fractions={2} .. emptySymbol={<Icon name="star" />} />
..
```

**This doesn't:** ( .. name="star **_outline_**" ..)
```
import Rating from "react-rating";
import { .. Icon } from "semantic-ui-react";
..
<Rating fractions={2} .. emptySymbol={<Icon name="star outline" />} />
..
```

I also tried putting it into a variable and then passing in:
_this worked:_
`const empty = <Icon name="star" />;`

_this didn't:_
`const empty = <Icon name="star outline" />;`

PS.
When I say "didn't work" I mean, it detected the first word - star and ignored whatever came after space.

Also tried replacing space with dash ( - ) and using camelCase for the name.

Would love to find out what I'm doing wrong.

Cheers

**Comment by dreyescat** [comment]
Weird...

This component sees the `Icon` you are passing as a React Element. I mean, it doesn't matter how complex React Element are you passing to its `emptySymbol` property that no *parsing* is performed inside the `< />` that creates the React Element.

**Comment by dreyescat** [comment]
I was curious so I have created a small sample showing it working. Check this [CodeSandbox](https://codesandbox.io/s/zqx6mnxo4p). Hope it helps.

**Comment by ScottAgirs** [comment]
Hey @dreyescat thanks for the reply.

That's what I was thinking too.. I tried reinstalling react-rating and created a plain functional component to test it out.

Unfortunately, the same thing happens, only the full start ("star") is being rendered.
I also tried switching fullSymbol to emptySymbol, that didn't help either, also tried to change the initialRating value, made no difference.

perhaps my package.json file could help:
```

{
  "name": "yogabun",
  "private": true,
  "scripts": {
    "start": "meteor run"
  },
  "dependencies": {
    "@babel/runtime": "^7.0.0-beta.51",
    "apollo-client": "^2.3.7",
    "apollo-client-preset": "^1.0.8",
    "babel-plugin-inline-import": "^3.0.0",
    "bcrypt": "^3.0.0",
    "body-parser": "^1.18.3",
    "date-fns": "^1.29.0",
    "express": "^4.16.3",
    "faker": "^4.1.0",
    "google-map-react": "^1.0.6",
    "graphql": "^0.13.2",
    "graphql-server-express": "^1.4.0",
    "graphql-tag": "^2.9.2",
    "graphql-tools": "^3.1.1",
    "lodash": "^4.17.10",
    "meteor-node-stubs": "^0.4.1",
    "moment": "^2.22.2",
    "moment-duration-format": "^2.2.2",
    "react": "^16.4.2",
    "react-apollo": "^2.1.9",
    "react-dom": "^16.4.2",
    "react-map-gl": "^3.3.4",
    "react-places-autocomplete": "^7.2.0",
    "react-rating": "^1.3.2",
    "react-router-dom": "^4.3.1",
    "react-stripe-elements": "^2.0.1",
    "semantic-ui-calendar-react": "^0.8.0",
    "semantic-ui-react": "^0.82.2",
    "stripe": "^6.8.0",
    "styled-components": "^3.4.1"
  }
}

```

**Comment by dreyescat** [comment]
Hey @ScottAgirs! I'm pretty sure it is not a problem of this component.

My guess... Well, CSS is global and `outline` is not a strange name to use as a CSS class name. Maybe another package or CSS stylesheet is overriding it. Things I would do to try to isolate the problem:

1. Just show the same `Icon` without using it as a Rating symbol. Just show the icon `<Icon name="star outline" />`. I bet you'll have the same problem 😉.
1. Try using another `Icon` with a composed name. Try `<Icon name="thumbs down" />` and `<Icon name="thumbs down outline" />`. See what happens.
1. If the two previous steps points `outline` as the problem... You need to track *who* is defining it. Browser developer tools could be really helpul at this task.

I will close this issue. Feel free to open it again if you find out it is actually this component the issue.
