### ISSUE TITLE
React 15

### ISSUE THREAD

**Issue by joewood** [dreyescat/react-rating#11]
Could you update the dependencies for React 15 please?

**Comment by dreyescat** [comment]
Hi @joewood!

If I am not wrong it should be *compatible*. If you check [peerDependencies](https://github.com/dreyescat/react-rating/blob/v0.2.2/package.json#L38-L40) you will see that it depends on any react version above `>=0.13.0`.

```javascript
"peerDependencies": {
  "react": ">=0.13.0 || 0.14.0-rc1"
}
```

I assume `15` is included (rc are a different beast). Sometimes I get confused about semantic versioning but I checked with [semver calculator](http://semver.npmjs.com/) and if you select `react` with range `>=0.13.0 || 0.14.0-rc1` then version `15` is highlighted.

Anyway, let me know if it is not working for you.

**Comment by dreyescat** [comment]
I assume there is no need to increase React version.
