### ISSUE TITLE
Different fractions in placeholder and actual rating.

### ISSUE THREAD

**Issue by samansh82** [dreyescat/react-rating#110]
Hi, 
Is it possible to have different fractions when placeholder is being shown and when someone actually wants to rate? For example, component is able to show 4.5 stars as a placeholder (fraction=2) but users can rate only integer stars like 3, 4 or 5 stars (fraction =1).

**Comment by dreyescat** [comment]
Yes. You can. The `fractions` property only affects the selection not the placeholder. I mean, you can put whatever value you want as placeholder (4.5 for instance) because `fractions` is not applied to it.

Below you have a *whole* rating with a placeholder value of 4.5:

```jsx
<Rating  placeholderRating={4.5}  />
```
