### ISSUE TITLE
How to change Star rating color, by default is black.

### ISSUE THREAD

**Issue by mehuljariwala** [dreyescat/react-rating#112]
I need to change the color of the star.

Thanks 
Mehul Jariwala

**Comment by dreyescat** [comment]
The flexibility of this component resides in its symbols. You can use CSS, javascript styles or any React component to define your symbols. I will show you a couple of examples:

Using javascript styles:

```javascript
const style = {
  display: 'inline-block',
  borderRadius: '50%',
  border: '5px double white',
  width: 30,
  height: 30
};

const emptyStyle = {
  ...style,
  backgroundColor: 'green'
};

const fullStyle = {
  ...style,
  backgroundColor: 'red'
};

<Rating fullSymbol={fullStyle} emptySymbol={emptyStyle}/>
```

Using CSS and [fontawesome](https://fontawesome.com/) icons:

```css
.empty {
  color: green;
}

.full {
  color: red;
}
```


```javascript
<Rating emptySymbol="fa fa-star-o fa-2x empty" fullSymbol="fa fa-star fa-2x full"/>
```

Check this [codepen](https://codepen.io/dreyescat/pen/ZqPeLr).

**Comment by dreyescat** [comment]
I am closing this issue assuming the question is properly answered. Reopen it otherwise.
