### ISSUE TITLE
Move type file DefinitelyTyped repo

### ISSUE THREAD

**Issue by KyleDavisDev** [dreyescat/react-rating#116]
Hey,

I created a pull request in the [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) project a few days ago  [#30854](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30854) as this is more of the standard for libraries which were not originally created in TS. So much so that when you are working with a repo and it isn't typed, npm suggests you to look into the DefinitelyTyped repo to find typings.

As @minestarks pointed out in my PR, it doesn't make sense to have type files in both projects so I am wondering what you think about removing the type file from here (since this is the standard and you wont have to maintain the file any longer), and hosting is solely in DefinitelyTyped?

Let me know and I can create a PR here for you.

Thanks

**Comment by KyleDavisDev** [comment]
Good to know! Is that still the case even if library author does not maintain? As in, I think I read in an old pull request that @dreyescat  is not extremely familiar with typings and so so would only include what other people have submitted. This was part of the motivation, in my mind, to remove the file from this library and move is somewhere else.

In any case, if you believe the type file would be best suited here, then we should go with that.

Thanks

**Comment by dreyescat** [comment]
As @KyleDavisDev says I am not very familiar with typings 😞. However I am open to accept PR from other contributors.

**Comment by KyleDavisDev** [comment]
Hey @dreyescat  I didn't mean to sound harsh if it came off that way. I want whatever is best for the library whether that means you manage the PRs for something you are not familiar with or moving the typings get moved to a typings library.

**Comment by dreyescat** [comment]
Thanks @KyleDavisDev. Closed after merging #117.
