### ISSUE TITLE
How to show text or tooltip e.g (bad, good, very good) on each star?

### ISSUE THREAD

**Issue by sarmadzaki** [dreyescat/react-rating#119]

**Comment by dreyescat** [comment]
This component is very flexible in what you can use as symbols. You can use inline style objects, CSS classes, react elements or an array of them.

The question is a little bit vague so I am going to assume two options:

1. If what you want is to show a text somewhere when the symbol is hovered you could just use the `onHover` callback to populate the label with the desired text:

    ```jsx
    <Rating
      onHover={(rate) => document.getElementById('label-onrate').innerHTML = rate || ''}
    />
    ```
1. If what you want is to show a tooltip, well, there are many different implementations available. I could name, off the top of my head, using `title` attribute, using CSS, using javascript, or even react component. Just search for it and pick the one best fits your requirements. Check this example [using the `title` attribute](https://codepen.io/dreyescat/pen/mvNRxq):

    ```jsx
    const TooltipRating = ({tooltips}) =>
      <Rating
        stop={tooltips.length}
        emptySymbol={<span class="fa fa-star-o fa-2x" />}
        fullSymbol={tooltips.map(tooltip => <span class="fa fa-star fa-2x" title={tooltip} />)}
      />;

    <TooltipRating tooltips={['bad', 'good', 'very good']} />
    ```
