### ISSUE TITLE
iOS onChange and onRate functions are not firing. 

### ISSUE THREAD

**Issue by sushilk1991** [dreyescat/react-rating#12]
When the user clicks on the stars for the first time, it's not firing the onChange or onRate function.

**Comment by dreyescat** [comment]
With this info it is hard to give some help... Which browser? Which version of iOS? Only the first click/tap?

Does [Alert when rate changes](http://dreyescat.github.io/react-rating/) show an alert when you click/tap on a rate? This example is using the `onChange` callback.

**Comment by sushilk1991** [comment]
@dreyescat I am using iOS 9.2, safari browser. It does fire OnChange and onRate but only after the second tap, not for the first tap.

**Comment by dreyescat** [comment]
Sorry for the late response.

I have only been able to try it on an iPad with iOS 9.3.2 (I think it is the most up to date version right now) and it worked for me. I tried on Chrome and Safari. I have not been able to reproduce what you say :disappointed:

**Comment by SylarRuby** [comment]
@sushilk1991 Maybe you need to:

```
onRate: function(rate){
  // do stuff with rate
}
```
