### ISSUE TITLE
No 0 stars rating is possible when using fractions=2

### ISSUE THREAD

**Issue by lishine** [dreyescat/react-rating#121]

**Comment by dreyescat** [comment]
Let's see if I understand... With 0 star rating you mean no star selected?

When you create a rating by default the `initialRating` value is set to 0. This means *no star selected* or *0 star rating*.

```jsx
<Rating fractions={2} />
```

If you want you can explicitely set it:

```jsx
<Rating fractions={2} initialRating={0} />
```

Check this [fractional rating](https://codepen.io/dreyescat/pen/MRyqLM) example.

Let me know if I misunderstood your question.

**Comment by lishine** [comment]
Thanks for answering!
Yes, you see in your example that I cannot click such as to set value to 0 stars

**Comment by dreyescat** [comment]
Yes. This is intended. It is up to you how to reset your rating. Usually a reset button does the job:

```jsx
class ResetRating extends React.Component {
  constructor(props) {
    super(props);
    this.state = {value: props.initialRating};

    this.handleClick = this.handleClick.bind(this);
  }

  handleClick(event) {
    this.setState({value: 0});
  }

  render() {
    return (
      <div>
        <Rating {...this.props} initialRating={this.state.value} />
        <button onClick={this.handleClick}>Reset</button>
      </div>
    );
  }
}
```

Check [button reset rating](https://codepen.io/dreyescat/pen/MRyqLM).

I have heard people resetting the rating clicking on the selected value. But you can use whatever method or way to reset your ratings.
