### ISSUE TITLE
Stars not rendering

### ISSUE THREAD

**Issue by muhammad-asad-26** [dreyescat/react-rating#125]
Hi,
I'm using star-rating to render stars and let users give the rating.

This is my code base, 
Tech stack: 

1. react 16.7.0
2. bulma 0.7.4

```
<div className="columns">
                      <div className="column is-6">
                        <label className="has-text-black subtitle is-4 is-marginless is-paddingless">
                          Quality of work
                        </label>
                      </div>
                      <div className="column is-6">
                        <Rating
                          emptySymbol="fas fa-star-o fa-2x"
                          fullSymbol="fas fa-star fa-2x"
                          placeholderSymbol="fas fa-star-o fa-2x"
                          fractions={2}
                        />
                      </div>
                    </div>
```

The problem is when I inspect the element the width is set to 0%

**Comment by dreyescat** [comment]
Hi @muhammad-asad-26, some things to check:
 
- Make sure you've included fontawesome CSS
- Check what version of fontawesome are you using (v4 or v5)
- Check the name of the symbol for the selected version

```javascript
<Rating
    emptySymbol="far fa-star fa-2x"
    fullSymbol="fas fa-star fa-2x"
    fractions={2}
/>
```

Check this [codepen](https://codepen.io/dreyescat/pen/wbrexx)

**Comment by muhammad-asad-26** [comment]
Hi @dreyescat 
I have included fontawesome CSS v5. This is working fine in a codepen. I have checked it independently but not working in combination with Bulma. The width seems to be override by 0% which is really weird.

**Comment by dreyescat** [comment]
@muhammad-asad-26 

Replace `fa-star-o` with `fa-star`. And for the `emptySymbol` use the `far` instead of `fas`. I think you are mixing fontawesome v4 and v5 symbol names.

Check this [codepen with Bulma](https://codepen.io/dreyescat/pen/XweeXE)

**Comment by muhammad-asad-26** [comment]
@dreyescat 
Thanks, you were right I didn't noticed that I was using **fas** instead of **far**.
