### ISSUE TITLE
onClick/onChange calls the value of rating, but not filling the star symbols

### ISSUE THREAD

**Issue by lixinge921111** [dreyescat/react-rating#126]
Hello! 

I came across a problem when trying to use the react-rating. I could successfully call the values of the rating using onClick or onChange. However, the stars of the rating is filled in color only when clicked the second time on the same rating. Here is how my code looks like (in react hooks):

const [Rate, setRate] = useState(0);

return ( <Rating
          emptySymbol={<Icon className="primary">star</Icon>}
          fullSymbol={<Icon color="secondary">star</Icon>}
          onClick={value => {
            setRate(value); 
          }}
        />) 

Am i missing something here?
Thank you very much!

**Comment by dreyescat** [comment]
Hi @lixinge921111!

As you are keeping the state outside of the `Rating` component with the `useState` hook, you need to *plug* the `Rate` value to the `Rating` component. You just need to *bind* the `initialRating` to your `Rate` state:

```javascript
  const [Rate, setRate] = useState(0);
  
  return (
    <Rating
      emptySymbol={star}
      fullSymbol={star}
      onClick={setRate}
      initialRating={Rate}
    />
  );
```

Check this [codepen](https://codepen.io/dreyescat/pen/oRmPbj).

**Comment by lixinge921111** [comment]
Thank you very much! We fixed the problem :)

**Comment by lixinge921111** [comment]
It works now :) Thanks again!
