### ISSUE TITLE
Image not hovering 100%

### ISSUE THREAD

**Issue by guille-alibrate** [dreyescat/react-rating#130]
I'm using this setup:

> start={0}
> stop={10}
> step={2}
> fractions={2}

And values like:
5
3.5
3

Some values, like 3.5, will not cover the underlaying image completely:

![image](https://user-images.githubusercontent.com/56847061/68331040-01f1ef00-00b3-11ea-8905-d877f9881409.png)

What could it be?

**Comment by guille-alibrate** [comment]
2.5 looks like this:

![image](https://user-images.githubusercontent.com/56847061/68331302-88a6cc00-00b3-11ea-82ec-93c75bfea5b4.png)

**Comment by guille-alibrate** [comment]
For 3.5, I'm inspecting the code and it says width: 75%
For 2.5, second start says width: 25%

**Comment by guille-alibrate** [comment]
Nevermind. I removed most of my previous config, just left fractions={2}, and works like a charm

**Comment by dreyescat** [comment]
Closing as no action is required.
