### ISSUE TITLE
Error during installation on jenkins

### ISSUE THREAD

**Issue by karunkamal** [dreyescat/react-rating#137]
The module runs fine on local machine, but when i push it on server, it fails due to underlying issue: 

20:53:12 ~/pathToApp/node_modules/@types/react/index.d.ts
20:53:12 TypeScript error: Duplicate identifier 'LibraryManagedAttributes'.  TS2300
20:53:12 
20:53:12     2816 |         // We can't recurse forever because `type` can't be self-referential;
20:53:12     2817 |         // let's assume it's reasonable to do a single React.lazy() around a single React.memo() / vice-versa
20:53:12   > 2818 |         type LibraryManagedAttributes<C, P> = C extends React.MemoExoticComponent<infer T> | React.LazyExoticComponent<infer T>
20:53:12          |              ^
20:53:12     2819 |             ? T extends React.MemoExoticComponent<infer U> | React.LazyExoticComponent<infer U>
20:53:12     2820 |                 ? ReactManagedAttributes<U, P>
20:53:12     2821 |                 : ReactManagedAttributes<T, P>

20:53:12 error Command failed with exit code 1.
20:53:12 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by dreyescat** [comment]
Hi @karunkamal 

I don't really why do you suppose this error is due to this component? I only see a TypeScript error :confused:.

**Comment by dreyescat** [comment]
Closing because I don't see clear why this issue is related to this package.
