### ISSUE TITLE
Better example

### ISSUE THREAD

**Issue by SylarRuby** [dreyescat/react-rating#14]
How to change stars etc? Give examples please.

Are you going to update this? Nothing works. No props work. fractions does nothing.

**Comment by dreyescat** [comment]
> How to change stars etc? Give examples please.

Documentation is not the strong point of this repo but you can find some examples if you check the  [demo](http://dreyescat.github.io/react-rating/) page.

> Are you going to update this? Nothing works. No props work. fractions does nothing.

Could you be more specific? I might try to help you out. Could you create a fiddle reproducing your issue? You can base your code on this [fractional rating fiddle](https://jsfiddle.net/dreyescat/0pe6z9q2/).

**Comment by SylarRuby** [comment]
Ok, fractions part cleared up as I was doing `fractions={this.state.franctions} //=> 0.5`

Another issue though:

```
...

foo: function(rate){
 this.setState({ xxx: rate });
},

bar: function(e){
 this.setState({ xxx: e.target.value });
},


<Rating onClick={this.foo} />
<textarea type="text onChange={this.bar) />

```

With the above, once I start to type in the text area, my selected starts are unselected. Why? `e.preventDefault();` does nothing. The state is still there but my rating is now unselected.

**Comment by dreyescat** [comment]
Because every time you change the `state` your `render` function is called again. So, as I guess by  your code, you are re-rendering an empty `Rating` again and again.

Maybe what you need is something like a [controlled component](https://facebook.github.io/react/docs/forms.html#controlled-components) but with a rating instead of an `input`:

```javascript
var MyComponent = React.createClass({
  getInitialState: function () {
    return {
      xxx: 1
    };
  },
  foo: function (rate) {
    this.setState({xxx: rate});
  },
  bar: function (e) {
    this.setState({ aaa: e.target.value});
  },
  render: function () {
    return (
        <div>
    	    <Rating onChange={this.foo} initialRate={this.state.xxx} />
            <textarea type="text" onChange={this.bar} />
        </div>
    );
  }
});

ReactDOM.render(
  <MyComponent />,
  document.getElementById('container')
);
```

With this code you ensure that you take over "control" of the rate value, because you are now keeping it in your internal state.

**Comment by SylarRuby** [comment]
@dreyescat Ok, buddy. All is well. Keep up the good work. Thanks.
