### ISSUE TITLE
Misalignment

### ISSUE THREAD

**Issue by polkadotazn** [dreyescat/react-rating#142]
Hey, cool package. I first used this in my app in 2018. I used a custom icon, and everything worked great. I came back to this project this year, updated everything and now (though I hadn't touched the react-rating component) it seems like my icons are misaligned. I looked into it and for some reason my "emptySymbol"s  are not getting the span style anymore while the "fullSymbol"s still are. Any advice? Here are some pics that show what is happening.
![image](https://user-images.githubusercontent.com/10870123/82462274-5ece5900-9a89-11ea-8e23-9002e8cb7f37.png)
![image](https://user-images.githubusercontent.com/10870123/82462281-6130b300-9a89-11ea-985f-3dd370a4d081.png)

**Comment by polkadotazn** [comment]
Also, I know it's not my image because on my site, even with the outdated broken image (different image) the alignment is off.

**Comment by dreyescat** [comment]
Hi @polkadotazn! Nice to know you are repeating after 2 years :confetti_ball:

I would like to try to reproduce the issue in a more isolated environment. I kind of tried to guess what you are (were) doing. I have just created a quick [codepen](https://codepen.io/dreyescat/pen/eYpbQvd) with a working example. Feel free to modify and adapt to your needs and let's see if I can help you figure out what is going on.

My assumptions:
 - You are using the v2 of this package
 - You are trying to use a custom image as icons

Let me know if I missed something.

**Comment by polkadotazn** [comment]
Hey, thanks for your quick reply! I actually just found the problem. I was trying to modify the position of the container span and it was only the fullSymbol but not the emptySymbol. I see now that the empty symbol is left without styling on purpose, and that seems to be why trying to modify the containing span affected the empty symbol differently. Phew :)

**Comment by polkadotazn** [comment]
And yes btw haha I'm glad to be fixing up my project finally after all this time 😂
