### ISSUE TITLE
Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code. See https://reactjs.org/link/unsafe-component-lifecycles for details.

### ISSUE THREAD

**Issue by ayushbafna24** [dreyescat/react-rating#147]
Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code. See https://reactjs.org/link/unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://reactjs.org/link/derived-state

Please update the following components: Rating, RatingAPILayer

**Comment by ayushbafna24** [comment]
please help on a immediate basis

**Comment by ayushbafnajalhar** [comment]
@dreyescat please help.we are waiting for a kind response

**Comment by dreyescat** [comment]
There is an exact issue like this already #146 . Please check it out. It is marked as help wanted. I'm busy now with other stuff so any pull request is really welcome.

**Comment by ayushbafna24** [comment]
Please add me in this repository.I will help you for this issue

Regards,
Ayush

**Comment by dreyescat** [comment]
It easier than that :wink: .

You do not need to depend on me. Just fork the repo and you will have a copy of your own where you can do whatever you consider fits your needs. Then, afterwards, if you want, you can create a pull request.

Check [this](https://opensource.com/article/19/7/create-pull-request-github) if you are not really sure what a fork and pull request are.

Hope it helps
