### ISSUE TITLE
Support `rate` props to control UI.

### ISSUE THREAD

**Issue by Beingbook** [dreyescat/react-rating#16]
This component can't cancel rate if user rated.
To solve this, `rate` props is needed.

**Comment by dreyescat** [comment]
If I am not wrong, what you mean is having a [controlled react rating](https://facebook.github.io/react/docs/forms.html#controlled-components). You can create a wrapper component that maintains the rate value in its own internal state. Then, you can use whatever you want to reset the rating, for example, a reset button:

```javascript
var MyComponent = React.createClass({
  getInitialState: function () {
    return {
      rate: undefined
    };
  },
  onReset: function () {
    this.setState({rate: undefined});
  },
  onChange: function (rate) {
  	this.setState({rate: rate});
  },
  render: function () {
    return (
        <div>
            <Rating onChange={this.onChange} initialRate={this.state.rate} />
            <button onClick={this.onReset}>Reset</button>
        </div>
    );
  }
});
```
Check this [rating reset](https://jsfiddle.net/dreyescat/oeph4qcf/) example.

Hope I did not misunderstand your comment :wink:.

**Comment by Beingbook** [comment]
Oops! I misunderstood this component. Thank you!
