### ISSUE TITLE
setting initialRate  to a fraction e.g. 3.5

### ISSUE THREAD

**Issue by hareeqi** [dreyescat/react-rating#2]
I couldn't set the initialRate  to a fraction and see partial stars, after more digging i found out the problem in the indexOf function and to be more specific the use of Math.floor

i changed this 

return Math.max(Math.floor((rate - range.start) / step), 0);

to 

return Math.max(((rate - range.start) / step).toFixed(1), 0);

Not really sure if it will break anything though

**Comment by dreyescat** [comment]
Thanks for the feedback!

`indexOf` should not be restricted to whole indexes as we can have fractional ones. So, you are right, `Math.floor` should be removed.

The new version should include this fix.
