### ISSUE TITLE
Rating doesn't persist when using setState within onChange/onClick/onRate

### ISSUE THREAD

**Issue by sstawecki** [dreyescat/react-rating#22]
Hi, I'm having issues after doing a setState within onClick...there are  no errors, the state is set, but the elements in the view are not being filled, the span style for all filled elements has width: 0%
I did a workaround by defining a global "let score" instead of using setState but I know that is not a good solution.

render()
```
<div className="rate-wrap">
    <Rating
      empty={"icon-star-filled"}
      full={"icon-star-filled active"}
      onChange={this.handleScore}
    />
</div>
```

```
handleScore(s) {
    // score is global, it should be this.setState({score:s}); but doesn't work
    score = s;
  }
```

What am I doing wrong?
Thanks!
Sebastian

**Comment by dreyescat** [comment]
Uhmm... `onClick`, `setState`... This looks familiar to me. Could you check #16?

It seems you are trying to _wrap_ the `Rating` component within another one that keeps the state. So the `Rating` becomes what I like to call [controlled component](https://facebook.github.io/react/docs/forms.html#controlled-components).

Let me know if I missinterpreted your issue.

**Comment by sstawecki** [comment]
Thanks for your time! there was missing the initialRate prop in my code

```
                  <Rating
                    initialRate={this.state.score}
                    empty={"icon-star-filled"}
                    full={"icon-star-filled active"}
                    onChange={this.handleScore}
                  />
```
I have added it and now it is working like a charm, thanks again!!

**Comment by Koerner** [comment]
If someone has the same problem. For version >1.0 it should be `initialRating={this.state.score}` instead of `initialRate={this.state.score}`
