### ISSUE TITLE
onClick event doesn't get event as parameter

### ISSUE THREAD

**Issue by trickbz** [dreyescat/react-rating#29]
I need to call event.stopPropogation(), but onClick event passes only rating value..

**Comment by dreyescat** [comment]
A quick solution could be to pass the `event` as the second parameter of the `onClick` handler.

`onClick`   ->   `function (rate, event) {}`

I am used to see the `event` as the first parameter in the event handlers... but to keep backward compatibility we could just pass the `event` as the second parameter.

**Comment by dreyescat** [comment]
Just released [v0.6.2](https://github.com/dreyescat/react-rating/releases/tag/v0.6.2) with this little change.
