### ISSUE TITLE
Removing a rating

### ISSUE THREAD

**Issue by sleepycat** [dreyescat/react-rating#35]
Is there a way to go from ★☆☆☆☆ to ☆☆☆☆☆?
Being able to click the first star a second time and remove the rating entirely would be really nice.

**Comment by dreyescat** [comment]
You can take over control the `rate` just wrapping the rating component. For example, you could just check in the `onClick` handler if the `rate` is the same as the current one then reset it:

```javascript
var MyComponent = React.createClass({
  getInitialState: function () {
    return {
      rate: undefined
    };
  },
  onClick: function (rate) {
    if (this.state.rate === rate) {
      this.setState({rate: undefined});
    }
  },
  onChange: function (rate) {
    this.setState({rate: rate});
  },
  render: function () {
    return (
        <div>
            <Rating onChange={this.onChange} onClick={this.onClick} initialRate={this.state.rate} />
        </div>
    );
  }
});
```

Check this [jsfiddle](https://jsfiddle.net/dreyescat/n0jz4rfu/) with a running example.
