### ISSUE TITLE
Flicker issue on mousemove when getBoundingClientRect() returns non integer values.

### ISSUE THREAD

**Issue by raianand** [dreyescat/react-rating#38]
https://github.com/dreyescat/react-rating/blob/8043bbcaa1c855f5d29b4ed7bb032703c9e20885/src/Rating.jsx#L158-L163

Since getBoundingClientRect()  can return sub-pixel values and clientX/Y are always rounded off, it causes flicker while mouse moves from one star to next for 1 pixel. I was able to fix this by using Math.floor on values returned by getBoundingClientRect().

**Comment by dreyescat** [comment]
@raianand It smells like issue #36. Which broswer are you having this issue? I was only able to reproduce it on the 32-bit version of Chrome. The 64-bit version worked *well*.

**Comment by raianand** [comment]
@dreyescat  I am using Chrome Version 55.0.2883.95 (64-bit).

**Comment by dreyescat** [comment]
Thanks @raianand. This is helpful because I was only able to test it on Linux and Windows. So... It seems to happen on Chrome, regardless it is 32-bit or 64-bit version. Not happening neither on Firefox nor Edge (IE).

**Comment by dreyescat** [comment]
@raianand Does your fix works consistently on all browsers? I mean fixing this the way you propose does not break the behaviour in the other browsers?

**Comment by raianand** [comment]
@dreyescat I checked on FF/Safari/Chrome on mac and the fix was working. I was not able to spot any break in behaviour. 
Due to changes in product requirements, i am no longer using it now. So i cannot be absolutely certain of the fix being bug-free. But there were no obvious issues.

**Comment by dreyescat** [comment]
Ok. I will give a try and see if it solves the issue 👍.
