### ISSUE TITLE
Integration of onHover

### ISSUE THREAD

**Issue by Zephir77167** [dreyescat/react-rating#42]
Hi,

I feel like onHover is missing from the callbacks of your component (which my team and I have been using for a year now, thanks a lot!). It could pass the value of the hovered score, and would be useful to display some text under the Rating Component, to explain the meaning of each score.

Please let me know if you want do it or if I should do a PR.

Thanks for your work!

**Comment by dreyescat** [comment]
If I did not misunderstand, [`onRate`](https://github.com/dreyescat/react-rating#callbacks) is what you are looking for. Maybe the name is misleading but this callback is called every time you hover over a rate. It is a *onHoverRate*.

```
<Rating empty="fa fa-2x fa-star-o" full="fa fa-2x fa-star" fractions={2}
       onRate={function (rate) {
         // Show your score here.
       }}/>
```

Check this [fiddle](https://jsfiddle.net/dreyescat/97qttgvr/).

Let me know if this is not what you need and of course a PR would be welcome.

**Comment by Zephir77167** [comment]
You're right, I misread the documentation!

Thanks for your answer, and thanks again for your work!
