### ISSUE TITLE
Prepare for React 16: Deprecated React.CreateClass

### ISSUE THREAD

**Issue by stueynet** [dreyescat/react-rating#43]
Gotta remove CreateClass prior to version 16. Seems to only be in 4 files:

https://github.com/dreyescat/react-rating/search?utf8=%E2%9C%93&q=React.CreateClass&type=

PercentageSymbol: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

**Comment by dreyescat** [comment]
A bunch of deprecations to face 😅. Let's do one at a time. For now I have solved the `createClass` with the easy option (I am thinking about moving the entire component to es6 as a long term solution).

Also migrated `TestUtils` from deprecated react-addons to `react-dom/test-utils`.

Pending:
- PropTypes

**Comment by Kornil** [comment]
I proposed a fix for PropTypes here https://github.com/dreyescat/react-rating/pull/47 let me know if you have any feedback
