### ISSUE TITLE
Error: addComponentAsRefTo when importing a lib using react-rating

### ISSUE THREAD

**Issue by litil** [dreyescat/react-rating#53]
I have a component A which imports and uses the Rating component from react-rating. If I use this component A in my application, there is no issue.

But lately, I started to create my own component library and I moved component A into this library. Now, I have the following error:

`invariant.js?da6c:44 Uncaught (in promise) Error: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner)`

If I remove the code where I use the Rating component from my component A, the error disappear. I tried to add react-rating in the "externals" array of my webpack config, but it didn't help.

Any idea on how to fix that?

**Comment by dreyescat** [comment]
Not sure if I can help but here you have some thoughts:
- I am pretty sure it is a webpack configuration issue.
- I bet it is the second part of the message that causes the error `you have multiple copies of React loaded`. Can you check in the generated app bundled file if you have `React` library twice? And how many times in your component library?
- If I have not misunderstood, you are creating your own component library that is imported and used from your app. Maybe you are not excluding `React` from your library (check how I do this in [webpack.config](https://github.com/dreyescat/react-rating/blob/v0.8.0/webpack.config.js#L39-L47)). If you do not exclude it from your library then you can have it twice. One coming from your app and the other from your library.

In pull request #40 the `src` was included so you can *re-webpack* at your will. I have never tried but it means you can `import` the `Rating` component *directly* into your component library as if it was yours without having to use it as a library.

Hope it helps!

**Comment by litil** [comment]
Thanks for your answer @dreyescat, I fixed the issue by adding this to my webpack configuration file:
`
resolve: {
    ...
    alias: {
            'react' : path.resolve(__dirname, 'node_modules/react')
    },
}
`

By doing so, I'm telling the application to load react from a specific path. It won't try to load react from my library.
