### ISSUE TITLE
Warnings when using readonly mode

### ISSUE THREAD

**Issue by bslinger** [dreyescat/react-rating#58]
We use react-rating in readonly mode a lot, but we are receiving warnings for the mouse and touch events as they seem to get passed to the child as boolean false instead of null as would be expected. eg: `Warning: Expected 'onMouseLeave' listener to be a function, instead got a value of 'boolean' type.`

It looks like the cause is the checks for readonly here: https://github.com/dreyescat/react-rating/blob/master/src/Rating.jsx#L172 - those expressions return false.

**Comment by dreyescat** [comment]
Pull request #57 should solve this issue. Let me know otherwise 😉 .
