### ISSUE TITLE
Update propTypes usage from the package

### ISSUE THREAD

**Issue by Aftabnack** [dreyescat/react-rating#64]
## React 16

* Code breaks on React 16 since the `propTypes` have been removed from the default `react` variable.
* Code needs to change to use `propTypes` from the `prop-types` package

* Source
https://github.com/dreyescat/react-rating/blob/02fdc273044be1d92b07aad6d1d0a83ecb91c6c8/src/RatingAPILayer.jsx#L1

**Comment by mkarajohn** [comment]
@Aftabnack thanks! Please let me know if you still face issues.
