### ISSUE TITLE
Ability to select root element type and pass remaining properties to root element

### ISSUE THREAD

**Issue by darkowic** [dreyescat/react-rating#68]
Hello!

I want to user ReactRating component together with styled-components and style root component a little bit. But this is not possible because remaining properties like `className` are not passed to the root component. Also would be great if there is a possibility to choose root component type.

Great simple project btw :) Cheers!

**Comment by dreyescat** [comment]
I agree on propagate `other` properties that are not rating specific to its root/container element 👍.

> Also would be great if there is a possibility to choose root component type.

Not sure I understand your point here... You mean instead of the `span` element having another element as the container element?

**Comment by darkowic** [comment]
> Not sure I understand your point here... You mean instead of the span element having another element as the container element?

Yes. I will not use it probably right now but maybe someone will need it. Maybe let's wait for more comments about it.

**Comment by darkowic** [comment]
@mkarajohn 
> Please remove passing other props. Let's open an issue to discuss any specific additions you'd like to see to the API. I don't really like the idea of mass passing of undocumented props.

Here is the discussion. In my case most important property to pass is `className`. I do not see any problem with passing all other properties.

**Comment by mkarajohn** [comment]
Ok, so you would like to be passing a `className` and a `renderAs`/`wrapperComponent` prop that defines what kind of component wraps the rating symbols, correct?

**Comment by dreyescat** [comment]
FYI: I have had a deja vu... #13. I remember being wary about propagation. But it seems that pragmatism won.

**Comment by mkarajohn** [comment]
@dreyescat Passing `className` kinda makes sense I suppose (if it gets applied to the symbols' wrapper element). I don't think we will ever need to propagate props to symbols, since the user already has all the freedom in the world to pass whatever kind of symbol they would like. 

@darkowic if @dreyescat feels the same I think we can add the `className` as an optional expected prop, that gets applied to the wrapper element of the symbols. But let's ust stick to that for now.

**Comment by dreyescat** [comment]
@mkarajohn I agree to only propagate to the wrapper element. 

What we propagate... Yep, we can stick to selective propagation to what right now makes sense, i.e. `className`.

**Comment by darkowic** [comment]
Ok then. I can handle it to the end in my mr. We will pass only `className` property

**Comment by dreyescat** [comment]
Solved in #96
