### ISSUE TITLE
Svg as rating placeholder and hovering is broken

### ISSUE THREAD

**Issue by darkowic** [dreyescat/react-rating#69]
The example for an svg element is not working. http://dreyescat.github.io/react-rating/

I can not use the new release because of this bug.

**Comment by mkarajohn** [comment]
Noted, will get onto it as soon as I have some time available today. Or
feel free to give it a try yourself in the meantime :)

**Comment by darkowic** [comment]
Problem is that svg hovering area is very small. When you hovering at the bottom of rating icons it works correctly. I'm trying to debug it locally

**Comment by darkowic** [comment]
This is problem with calculating value under cursor somewhere in function `calculateDisplayValue`

**Comment by darkowic** [comment]
I solve the problem. I will post pull request soon

**Comment by ishake** [comment]
I'm having the same issue. Hoping the fix will be merged soon. :)

**Comment by darkowic** [comment]
@mkarajohn @dreyescat Pull request waits for merge and publish :)

**Comment by dreyescat** [comment]
Merged and released 👍. Thanks for the fix @darkowic.
