### ISSUE TITLE
w3c validation throws error

### ISSUE THREAD

**Issue by krzysu** [dreyescat/react-rating#7]
Hi,
it's not a big deal but on this line there is a basic w3c validation issue
https://github.com/dreyescat/react-rating/blob/master/src/PercentageSymbol.jsx#L60
"Element div not allowed as child of element span"

would you consider changing it to span?

**Comment by dreyescat** [comment]
Yep. It totally makes sense :+1: . I missed the inline only containing inline elements rule. I even set the `display` attribute of this `div` element to `inline-block`!

Would you mind to create a pull request?

**Comment by krzysu** [comment]
pull request created, is it enough?

**Comment by krzysu** [comment]
will you create a new release too? I need new version available in npm

**Comment by dreyescat** [comment]
Yep. I will do in a moment :+1:

**Comment by krzysu** [comment]
thank you!

**Comment by dreyescat** [comment]
@krzysu Done.
