### ISSUE TITLE
My first click on the rating doesnt return a value unless I click a 2nd time

### ISSUE THREAD

**Issue by MrAbalogu** [dreyescat/react-rating#75]
<Rating
      stop={10}
      fractions={2}
      onClick={this.submitRating.bind(this, this.props.id)}
 />;

I have used both the onChange and onClick methods but still I have to click a 2nd time for it to return a value. Please what is going on?

**Comment by dreyescat** [comment]
Uhm... It is weird. I tried this:

```jsx
<Rating onChange={rate => alert(rate)} />
```
It simply alerts when the rate changes. It seems to work. Check this [codepen](https://codepen.io/dreyescat/pen/WMwXKR)

**Comment by dreyescat** [comment]
Hey @MrAbalogu, could you try if the new release [1.0.5](https://github.com/dreyescat/react-rating/releases/tag/v1.0.5) solves this issue? I couldn't reproduce your behaviour. Could you give me a reproducible scenario? Nothing fancy. Something that helps me reproduce it, like issue #76.

**Comment by MariaRoblesSpin** [comment]
I have exactly the same problem. But you're right, @dreyescat. If I try this `<Rating onChange={rate => alert(rate)} />` the alert shows me the correct number. But If I put my handleRating function it works wrong... this is my handleRating function `_handleRating = (value) => {
    try {
      const { rating } = this.state
      this.setState({ rating: value })
      const movie = this.props.movie
      console.log('Rating value in handleRating: ', rating)
      console.log('Movie value in handleRating: ', movie)
      this.props.onRating({ rating, movie })
    } catch (error) {
      console.log('error in handleRating: ', error)
    }
  }`
There is a mistake somewhere but I'm not able to find it.
Could you help me? 
Thank you in advance.

**Comment by dreyescat** [comment]
@MariaRoblesSpin I think you are showing the previous value, not the current one.

```javascript
const { rating } = this.state
```
This statement is assigning the previous rating value to the `rating` const variable. The new one is in the `value` parameter of the `_handleRating` function.

Maybe you think that the next `setState` call is updating this local variable... But it isn't.

**Comment by dreyescat** [comment]
I am not sure what you need... But if you want to call a callbag once the `setState` has completed I suggest using the `componentDidUpdate` method:

```javascript
  componentDidUpdate() {
    const { rating } = this.state;
    const { movie } = this.props;
    this.props.onRating({ rating, movie});
  }

  _handleRating = (value) => {
    this.setState({ rating: value });
  }
```

Check this [codesandbox](https://codesandbox.io/embed/callback-on-update-xed0z)

**Comment by Falci** [comment]
Same issue happened to me. 
I believe it happens when the `onChange` forces a re-render in the Rating component.

[Here](https://codesandbox.io/s/ancient-dawn-nepb4?file=/src/App.js)'s a small reproducible example.

**Comment by Falci** [comment]
> [Here](https://codesandbox.io/s/ancient-dawn-nepb4?file=/src/App.js)'s a small reproducible example.

Btw, I managed to solve it by adding the `initialRating`:
```javascript
<Rating onChange={setRate} initialRating={rate} />
```
