### ISSUE TITLE
Feature Request: Add an optional clear button.

### ISSUE THREAD

**Issue by davidklebanoff** [dreyescat/react-rating#78]
Add an optional clear button that clears the rating, and falls back to the placeholder rating if one exists.

Example:
http://plugins.krajee.com/star-rating-demo-theme-svg#theme-svg-ltr-star

**Comment by dreyescat** [comment]
Uhm... I am always wary of the idea of adding more properties. Yes, the example plugin is really nice! It is a great job! It has an option for anything you can imagine 😄. You have options for a clear button, captions, star captions, etc. And, hence, to give you more flexibility, many other properties to customize text and style of those options. It is a way. Giving you a full-featured component. It is Ok. Nothing against it.

But I prefer the other way. Let's call the *react* way. Give you the basics and let you *compose* your own. Create a new component that manages the `Rating` state at your will. With a reset button, for example:

```javascript
// ResetRating
class ResetRating extends React.Component {
  constructor(props) {
    super(props);
    this.state = {value: 0};

    this.handleClick = this.handleClick.bind(this);
  }

  handleClick(event) {
    this.setState({value: 0});
  }

  render() {
    return (
      <div>
        <Rating {...this.props} initialRating={this.state.value} />
        <button onClick={this.handleClick}>Reset</button>
      </div>
    );
  }
}
```
You are not limited to a specific way of resetting your value. Let your imagination fly 😉.

**Comment by dreyescat** [comment]
You can see it in action in [the demo page](http://dreyescat.github.io/react-rating/).

**Comment by davidklebanoff** [comment]
Sounds good, thanks!
