### ISSUE TITLE
Feature Request: Provide a way to programmatically alter result

### ISSUE THREAD

**Issue by wyqydsyq** [dreyescat/react-rating#79]
I have some custom logic in my function used for `onChange` where based on some condition, I want to alter the resulting value (specifically, setting it back to what it was). I think a slight change to the API of this would enable me to do this as well as enabling more customizability of this library in general:

If the signature for this function was changed to:
```ts
(value, oldValue) => value
```
And this library applied the return value to the UI (e.g. if my logic changes the value from 8 to 4, the rating component updates to reflect that as if the user selected 4 themselves) I would be able to implement what I'm going for. If the return could be a Promise that gets awaited before updating the UI would be even more ideal.

My specific use-case is that I want to measure `body.scrollTop` to see if the user is attempting to scroll vertically (`scrollTop` has changed compared to a previous measurement), and if so I want to revert the rating value back to what it was (since the user intended to scroll, not to rate)

**Comment by dreyescat** [comment]
If what you want is to alter the resulting value why not just take absolute control of the state? Let me explain. You can keep the rating state (in your case the rating value) in a different component that *controls* it similar to how it is done for [controlled components](https://reactjs.org/docs/forms.html#controlled-components).

Inside this component you decide if you want to go back to the previous value or not depending on the logic or condition you consider opportune.

You can even create your own `Rating` component with the `(value, oldValue) => value` signature. Something like this:

```javascript
class ControlledRating extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      value: props.initialRating
    };

    this.handleChange = this.handleChange.bind(this);
  }

  handleChange(value) {
    this.setState({
      value: this.props.onChange(value, this.state.value)
    });
  }

  render() {
    return (
      <div>
        <Rating {...this.props} onChange={this.handleChange} initialRating={this.state.value} />
      </div>
    );
  }
}
```

Then you can use it as the original one but with your own `onChange` signature. Here a contrived example using your proposed signature to only allow changes to the adjacent symbols of the selected one:

```jsx
<ControlledRating initialRating={3} quiet={true} onChange={(value, oldValue) => {return Math.abs(value - oldValue) > 1 ? oldValue : value}} />
```
You can play around with [in this codepen](https://codepen.io/dreyescat/pen/aqyNeK).

Hope it helps.

**Comment by wyqydsyq** [comment]
Ah excellent I had incorrectly assumed that this library only applied the `initialRating` prop in it's `constructor` but [looking into the source](https://github.com/dreyescat/react-rating/blob/master/src/RatingAPILayer.jsx#L17) I can see it also applies that prop to it's internal state in `componentWillReceiveProps` so it will react in response to a wrapping component changing that prop as in your example.

Thanks! 😄
