### ISSUE TITLE
Incoming props changing quickly can cause an incorrect `displayValue` to be set

### ISSUE THREAD

**Issue by joekrill** [dreyescat/react-rating#80]
I'm running into an issue where the underlying `Rating` component's `state.displayValue` is getting updated incorrectly. 

Here is a Codepen demonstrating the problem: https://codepen.io/joekrill/pen/NyeKpL

Note that hovering an icon momentarily, then moving the mouse out of the component completely continues to show the last hovered item instead of reverting back to the current value. This can vary a bit depending on how quickly the mouse is moved - if you're not seeing this behaviour try moving the mouse more slowly. Here's a gif of what I'm seeing (I'm not clicking anything at all here, just moving the mouse):

![feb-27-2018 15-38-49](https://user-images.githubusercontent.com/393220/36753528-67f83482-1bd4-11e8-8093-253eea93f113.gif)

This only seems to happen in some very specific scenarios. For example, doing any of the following will cause things to work "as expected":
1. Not setting the `initialRating` prop, or setting it to zero (`0`)
1. Not setting `fullSymbol` and `emptySymbol` props, or setting them to a string, or even precreating their components.
1. Removing the code that shows the "hoveredRating" value separately.

Ultimately I think the problem is that in the `Rating` component's `componentWillReceiveProps` method, `setState` is called by passing a new state object directly, and is using a reference to the current state (`this.state.displayValue`, in this particular case, line 5 below):

```js
componentWillReceiveProps(nextProps) {
    const valueChanged = this.props.value !== nextProps.value;
    this.setState({
      dirty: valueChanged || this.state.dirty,
      displayValue: valueChanged ? nextProps.value : this.state.displayValue
    });
  }
```

However, per the [the React docs](https://reactjs.org/docs/react-component.html#setstate), `setState` calls of this type are asynchronous and may be batched together. In this particular case, this can cause `this.state.displayValue` to be set based on an out-of-date previous `displayValue`. Which is why it is recommended that the updater function form of `setState` be used instead. So this should really be:

```js
componentWillReceiveProps(nextProps) {
    const valueChanged = this.props.value !== nextProps.value;
    this.setState((prevState) => ({
      dirty: valueChanged || prevState.dirty,
      displayValue: valueChanged ? nextProps.value : prevState.displayValue
    }));
  }
```

And indeed that seems to fix the problem in my testing.

So I think when props are changed in a certain way that causes `componentWillReceiveProps` to get called very soon after `onMouseLeave`, the `setState` calls get batched causing the wrong `displayValue` to get calculated. 

I'm still a little confused as to why exactly it is that certain things - like not setting `initialRating` - prevent the problem.  But that doesn't really change the fact that this `setState` call should be using an updater function since it's setting the new state based on the previous state. So I'll put up a PR for that at least.

**Comment by dreyescat** [comment]
I can see your codepen demonstrating this behavior. I have even tried your same codepen removing the `initialRating` and/or the `fullSymbol`/`emptySymbol`  and, as you say, it surprisingly works as expected! It's really weird...

The first thing I have done is just fork your codepen and try to create a *regular* wrapped component (without recompose): https://codepen.io/anon/pen/RQEmWG?editors=0011

Could you check I did it right? I mean, if this codepen corresponds to yours but without the `recompose` library?

I was trying to reduce it to its bare bones to help me figure out what was really causing this weird effect, but you know what? I cannot reproduce it 😅.

**Comment by mkarajohn** [comment]
>However, per the the React docs, setState calls of this type are asynchronous and may be batched together. In this particular case, this can cause this.state.displayValue to be set based on an out-of-date previous displayValue. 

That is definitely an error in the code, nice catch. I will take a look at the other things later tonight if I find the time.

**Comment by joekrill** [comment]
@dreyescat Yes that's the same. I only used recompose because that's what we've been using and I wanted to make sure I could reproduce it correctly. But I'm actually seeing the same (unexpected) behavior with your barebones codepen, so it's even weirder that you are not.

**Comment by dreyescat** [comment]
@joekrill My fault! You are completely right. I see the same unexpected behavior in my version.

**Comment by joekrill** [comment]
@dreyescat Oh good. It's a little finicky, too, depending on how quickly the mouse cursor moves, so maybe that's what was causing the confusion.

And thanks so much for getting this merged and updated no npm so quickly!
