### ISSUE TITLE
EDGE + SVG element buggy

### ISSUE THREAD

**Issue by madmus** [dreyescat/react-rating#83]
When an SVG(star) element is used, the middle of the SVG(star) is not registered as hover and thus no score can be given. Same issue lives on demo page with EDGE. The edges of the SVG(star) element can be hovered and clicked just not the middle. All other browsers seem to work fine.

i think the problem is the inner span which still is there, maybe a display none instead of a visible 0 would fix the problem

**Comment by dreyescat** [comment]
Yep. Microsoft Edge + SVG symbols is kinda buggy. I can see it even in the demo page 😅. If you move the mouse over the symbol (inside) I get a flickering effect for every mouse movement...

**Comment by madmus** [comment]
Well as it seems the fix is easy and can be done by CSS only. Do not know if this is the proper way but as it seems silent here I found this work around.

![screen shot 2018-06-05 at 11 03 53](https://user-images.githubusercontent.com/3205580/40966264-4e9ea970-68b0-11e8-85a9-79921c843eaa.png)

The most inner <svg/> and sibling <span/> must have a "pointer-events: none" and it wont flicker anymore in edge. See screenshot for html tree.

**Comment by dreyescat** [comment]
Thanks @madmus!

I fixed the demo page using your solution and it works. I just added this attribute to the `svg` element so it ignores the mouse events.

```
<svg  pointer-events="none"></svg>;
```

If anyone wants to use SVG icons I suggest to disable `pointer-events` for the `svg` elements containing the icon symbols. This gets rid of the undesired flickering on Microsoft EDGE.
