### ISSUE TITLE
Fraction ratings have odd hover problem w/ Material-Icons

### ISSUE THREAD

**Issue by RavenHursT** [dreyescat/react-rating#85]
You can see the issue here if you hover over the rating stars: https://codesandbox.io/s/264o06kwr

**Comment by dreyescat** [comment]
Well... This has been driving me crazy for a while... But I think I found out the cause.

If you try with other font icons, like `favorite` and `favorite_border`, then everything works as expected:

```jsx
<Rating
  emptySymbol={<FontIcon className="material-icons">favorite_border</FontIcon>}
  fullSymbol={<FontIcon className="material-icons">favorite</FontIcon>}
  fractions={2}
/>
```

So, why with the stars it doesn't work?

```jsx
<Rating
  emptySymbol={<FontIcon className="material-icons">star_border</FontIcon>}
  fullSymbol={<FontIcon className="material-icons">star_rate</FontIcon>}
  fractions={2}
/>
```
The only thing that changes is the name of the icon!!

Well, if you try this:

```jsx
<i className="material-icons" style={{outline: 'solid red'}}>star_rate</i>
<i className="material-icons" style={{outline: 'solid red'}}>star</i>
<i className="material-icons" style={{ outline: 'solid red' }}>star_border</i>
<i className="material-icons" style={{ outline: 'solid red' }}>favorite_border</i>
<i className="material-icons" style={{ outline: 'solid red' }}>favorite</i>
```
You will see that `star_rate` has a different width. It is larger than the others! This is what is causing this issue. This large width makes the icon to think that it is not yet more than 50% selected and hence reverse to first half when you stop moving your mouse over.

I don't know if it is intended the `star_rate` to have this width or it is a bug, but I just saw that there is another font icon called `star` that seems to have the desired width:

```jsx
<Rating
  emptySymbol={<FontIcon className="material-icons">star_border</FontIcon>}
  fullSymbol={<FontIcon className="material-icons">star</FontIcon>}
  fractions={2}
/>
```

Check this [code snippet](https://codesandbox.io/s/m344zlr4p8) with a summary of what I mean.

**Comment by RavenHursT** [comment]
Well shoot! This is perfect! Thanks!
