### ISSUE TITLE
onHover -> onStartHover and onEndHover

### ISSUE THREAD

**Issue by ratenbuuren** [dreyescat/react-rating#88]
**Current behaviour:**

When hover ends, the value is still visible:

![hover](https://user-images.githubusercontent.com/6205060/37945533-ea63684c-31aa-11e8-8cbb-998135efadc4.gif)

**Desired behaviour:**

When hover ends, the value is removed.

**To achieve:**

Split the onHover event to two events, one for starting to hover (mouse enter) and one for stopping the hover (mouse leave).

**Comment by dreyescat** [comment]
Nice catch! It was in the demo page in front of our eyes and I didn't even notice!

I have just released a new version [1.1.1](https://github.com/dreyescat/react-rating/releases/tag/v1.1.1) that fixes it.

I have adopted the same idea that we have in the previous [v0](https://github.com/dreyescat/react-rating/releases/tag/v0.9.1) version. When the hover ends the `onHover` callback is called with no value.
