### ISSUE TITLE
Get error when first click rating and key press input?

### ISSUE THREAD

**Issue by tranvanthuc** [dreyescat/react-rating#91]
You can see the video for more on this error
https://streamable.com/lvijt
or 
https://drive.google.com/open?id=1_oBwZmvdRjFceOkiDCZ8NgBJV16RTNBz
I integrated it with TextField of Material-UI
Please fix it, Thank you so much!

**Comment by dreyescat** [comment]
It is weird that it only happens with the first one and not with the second one 😕... Are you sure you are passing the proper `point` as `initialRating`?

Do you have some actual code I can look into? It would let us give you more help 😉.

**Comment by tranvanthuc** [comment]
Thanks for your reply. My code below, please check it.
`<div>
            {questions.map((question, index) => {
              return (
                <div key={index}>
                  <p>{question.content}</p>
                  <Rating
                    fractions={2}
                    onChange={rate => {
                    this.onChange(rate, question.id, index);
                    }}
                    emptySymbol={
                      <FaStar size={20} style={{ color: '#95a5a6' }} />
                    }
                    fullSymbol={
                      <FaStar size={20} style={{ color: '#f1c40f' }} />
                    }
                  />
                  <Field
                    name={'comment' + question.id}
                    component={CustomInput}
                    fullWidth={true}
                    multiLine
                    rows={4}
                    rowsMax={4}
                    hintText="Enter comment"
                  />
                </div>
              );
            })}
          </div>`

**Comment by tranvanthuc** [comment]
Thank you so much, I see and I tried it successfully. Thanks for your reply 😉
