### ISSUE TITLE
Typescript types

### ISSUE THREAD

**Issue by matus1997** [dreyescat/react-rating#93]
Hey, are you planning to add typescript definition file?

**Comment by dreyescat** [comment]
@szwarckonrad added TypeScript typings in pull request #87. I don't know very much about TypeScript definitions but I assume this is what you mean, isn't it?

**Comment by szwarckonrad** [comment]
@matus1997 Typings are in `/index.d.ts` and should be automaticaly loaded on `npm i react-rating`.
