### ISSUE TITLE
Add id or cssClass option to rating stars wrapper

### ISSUE THREAD

**Issue by abz121** [dreyescat/react-rating#96]
The component is awesome, but I need to style the parent wrapper (that holds individual stars) to things like align center. currently it doesn't have a css id and the props don't get passed through

**Comment by dreyescat** [comment]
You are not the first one requesting this kind of flexibility (#68). I think it makes sense to propagate the `className` to the wrapper element. I will take a look.

**Comment by dreyescat** [comment]
Now `id`, `style`, and `className` are propagated to the container element.

Released in version [1.2.0](https://github.com/dreyescat/react-rating/releases/tag/v1.2.0)

**Comment by mkarajohn** [comment]
I'll take care of publishing the new version to npm and updating the docs about this, during the weekend.
